spring:
  cloud: 
    gateway:
      white-List: 
        - aaaa
      routes:
        - id: netty-service
          uri: lb:ws://netty-service
          predicates:
            - Path=/forum/**
          filters: 
            - StripPrefix=1 
        - id: felix-user
          uri: lb://felix-user
          predicates: 
            - Path=/user/**
        - id: felix-book
          uri: lb://felix-book
          predicates:
            - Path=/book/**
# logging:
#   level:
#     org:
#       springframework:
#         cloud:
#           gateway: DEBUG
#     reactor:
#       netty:
#         http:
#           client: DEBUG